//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by AltoLib.AssetAddressCodeGenerator.
//------------------------------------------------------------------------------
namespace Personal
{
	public static class AssetAddress
	{
        public const string Actor_NPC_01                    = "Actor_NPC_01";
        public const string CashParent                      = "CashParent";
        public const string CubeBlue_Pickupable             = "CubeBlue_Pickupable";
        public const string CubeRed_Pickupable              = "CubeRed_Pickupable";
        public const string Dialog_1Button_Ok               = "Dialog_1Button_Ok";
        public const string Dialog_2Button_YesNo            = "Dialog_2Button_YesNo";
        public const string DialogButtonConfirmationBox     = "DialogButtonConfirmationBox";
        public const string Effects_Effect_01               = "Effects/Effect_01";
        public const string ItemParent_Day01_01             = "ItemParent_Day01_01";
        public const string MasterDataManager               = "MasterDataManager";
        public const string TransitionBrush                 = "TransitionBrush";
        public const string TransitionCircleWipe            = "TransitionCircleWipe";
        public const string TransitionDiagonalRectangleGrid = "TransitionDiagonalRectangleGrid";
        public const string TransitionDoubleWipe            = "TransitionDoubleWipe";
        public const string TransitionFade                  = "TransitionFade";
        public const string TransitionHorizontalCurtain     = "TransitionHorizontalCurtain";
        public const string TransitionLinearWipe            = "TransitionLinearWipe";
        public const string TransitionNoise                 = "TransitionNoise";
        public const string TransitionPaintSplash           = "TransitionPaintSplash";
        public const string TransitionRectangleGrid         = "TransitionRectangleGrid";
        public const string TransitionRectangleWipe         = "TransitionRectangleWipe";
        public const string TransitionTemplate              = "TransitionTemplate";
        public const string TransitionVerticalCurtain       = "TransitionVerticalCurtain";
    }
}
