//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by AltoLib.AssetAddressCodeGenerator.
//------------------------------------------------------------------------------
namespace Personal
{
	public static class AssetAddress
	{
        public const string Effects_Effect_01_prefab = "Effects/Effect_01.prefab";
        public const string MasterDataManager        = "MasterDataManager";
    }
}
