//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by AltoLib.AssetLabelCodeGenerator.
//------------------------------------------------------------------------------
namespace Personal
{
	public static class AssetLabel
	{
    }
}
