//------------------------------------------------------------------------------
// This file is AUTO-GENERATED by AltoLib.SceneNameCodeGenerator.
//------------------------------------------------------------------------------
namespace Personal
{
	public static class SceneName
	{
        public const string Main         = "Main";
        public const string PreloadScene = "PreloadScene";
        public const string Title        = "Title";
    }
}
